# Travis CI
#
#

sudo: required
dist: trusty
language: generic
python:
  - "2.7"

env:
  matrix:
    - "TESTDIR=PHP/cakephp"
    - "TESTDIR=PHP/codeigniter"
    - "TESTDIR=PHP/symfony2"

before_script:
  - source ./toolset/travis/travis_clean.sh
  - source ./toolset/travis/travis_setup.sh

script:

  # run-ci.py runs the diffing to see if travis needs to test this framework. Ideally/eventually,
  # we'd like to try and do the diffing before travis_clean & setup.
  # This will run the tests exactly as you would in your own vm:
  # ./toolset/run-tests.py --mode verify --test (all the valid tests for this framework)
  - tfb --mode verify --test-dir "$TESTDIR"
  # - tfb --mode verify --test

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.cache/pip
